name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get Current PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true
          filterOutDraft: true

      - name: Check PR Title Format
        run: |
          pr_title="${{ steps.PR.outputs.pr_title }}"
          regex_pattern="^(feat|fix|chore|docs|style|refactor|test)(\(.+\))?: .+"
          if [[ ! $pr_title =~ $regex_pattern ]]; then
            echo "error: Invalid PR title. Please follow the commit message convention."
            exit 1
          fi
