name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get Current PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true
          filterOutDraft: true

      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
        if: steps.PR.outputs.pr_found == 'true'
        env:
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}

      - name: Check PR Title Format
        run: |
          pr_title="${{ steps.pr_title.outputs.title }}"
          regex_pattern="^(feat|fix|chore|docs|style|refactor|test)(\(.+\))?: .+"
          if [[ ! $pr_title =~ $regex_pattern ]]; then
            echo "error: Invalid PR title. Please follow the commit message convention."
            exit 1
          fi
