name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check PR title
      run: |
        pr_title=$(git log --format=%s --no-merges -n 1 ${{ github.event.before }}..${{ github.event.after }})
        regex_pattern="^(feat|fix|chore|docs|style|refactor|test)(\(.+\))?: .+"
        if [[ ! $pr_title =~ $regex_pattern ]]; then
          echo "error: Invalid PR title. Please follow the commit message convention."
          exit 1
        fi
